config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from config import settings
from services.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home_page'),
    path('services/', include('services.urls', namespace='services')),
    path('doctors/', include('doctors.urls', namespace='doctors')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import UserCreateView, email_confirm, GeneratePasswordView, UsersDetail

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email_confirm/<str:token>/', email_confirm, name='email_confirm'),
    path('reset_password/', GeneratePasswordView.as_view(template_name='reset_password.html'),
         name='reset_password'),
    path('detail/<int:pk>', UsersDetail.as_view(), name='detail'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, verbose_name='Почта')

    first_name = models.CharField(max_length=150, verbose_name='Имя')

    last_name = models.CharField(max_length=150, verbose_name='Фамилия')

    avatar = models.ImageField(upload_to='users/photo', verbose_name='Аватар', blank=True, null=True,
                               help_text='Загрузите свой аватар')
    phone = models.CharField(max_length=35, verbose_name='Номер телефона', blank=True,
                             null=True, help_text='Введите номер телефона')
    country = models.CharField(max_length=35, verbose_name='Страна', blank=True,
                               null=True, help_text='Введите страну')
    token = models.CharField(max_length=100, verbose_name='Токен', blank=True, null=True, )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.forms import BooleanField

from users.models import User


class StyleFormMixin(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
                field.widget.attrs['placeholder'] = field.label
            else:
                field.widget.attrs['class'] = 'form-control'
                field.widget.attrs['placeholder'] = field.label


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2', )

users/views.py
import secrets
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.views import PasswordResetView
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, DetailView

from config.settings import EMAIL_HOST_USER
from users.forms import UserRegisterForm
from users.models import User


class UserCreateView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(20)
        user.token = token
        user.save(update_fields=['token', 'is_active'])
        host = self.request.get_host()
        url = f'https://{host}/users/email_confirm/{token}/'
        send_mail(
            subject='Подтверждение почты',
            message=f'Подтвердите вашу регистрацию перейдя по ссылке {url}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        return super().form_valid(form)


def email_confirm(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


class GeneratePasswordView(PasswordResetView):
    form_class = PasswordResetForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        if form.is_valid():
            email = form.cleaned_data['email']
            user = User.objects.get(email=email)
            if user:
                password = User.objects.make_random_password(length=8)
                user.set_password(password)
                user.save(update_fields=['password'])
                send_mail(
                    'Смена пароля',
                    f'Ваш новый пароль: {password}',
                    from_email=EMAIL_HOST_USER,
                    recipient_list=[user.email],
                )
            return redirect(reverse("users:login"))


class UsersDetail(DetailView):
    model = User
    template_name = 'users/user_detail.html'
    context_object_name = 'objects_list'

users/templates/login.html
{% extends 'services/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="POST" enctype="multipart/form-data">

        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        Войти
                    </button>
                    <a class="btn btn-primary" href="{% url 'users:reset_password' %}">Забыл пароль</a>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/personal_account.html
{% extends 'services/base.html' %}

{% block content %}
    <div class="col-12 text-center">
    <h1>
        Личный аккаунт
    </h1>
    <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выйти</a>
</div>
    <<div class="row">
    <div class="col-2 mx-auto">
        <div class="card mx-auto" style="width: 18rem;">
            <div class="card-body mx-20">
                <form method="post" enctype="multipart/form-data"></form>
                <h5 class="card-title">{% if object.first_name != '' and object.last_name != '' %} {{object.first_name}} {{object.last_name}} {% else %} {{object.email}} {% endif %}</h5>
                <img src="{{object.avatar | media_filter }}">
                <p class="card-text">Дата регистрации: {{object.date_joined}}</p>
                <p class="card-text">Последний вход: {{object.last_login}}</p>
                <p class="card-text">Подтверждён: {{object.is_verified}}</p>
                <p class="card-text">Менеджер: {{object.is_staff}}</p>
                <p class="card-text">Администратор: {{object.is_superuser}}</p>
                <p class="card-text">Заблокирован: {{object.is_block}}</p>
                <a href="{% url 'users:manager_users' %}" class="btn btn-md btn-outline-primary mx-auto">Назад</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/reset_password.html
{% extends 'services/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="POST" enctype="multipart/form-data">

        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        Изменить пароль
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}