config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from config import settings
from services.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home_page'),
    path('services/', include('services.urls', namespace='services')),
    path('doctors/', include('doctors.urls', namespace='doctors')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doctors/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from doctors.apps import DoctorsConfig
from doctors.views import (DoctorDetailView, DoctorListView, DoctorCreateView, DoctorUpdateView,
                           DoctorDeleteView)

app_name = DoctorsConfig.name

urlpatterns = [
    path('create/', DoctorCreateView.as_view(), name='create'),
    path('', DoctorListView.as_view(), name='home'),
    path('edit/<int:pk>/', DoctorUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', DoctorDeleteView.as_view(), name='delete'),
    path('detail/<int:pk>/', DoctorDetailView.as_view(), name='doctor_detail'), ]

services/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from services.apps import ServicesConfig
from services.views import (contacts, ServiceDetailView, ServiceListView, ServiceCreateView, ServiceUpdateView,
                            ServiceDeleteView, company, RecordCreateView, RecordListView, RecordDeleteView,
                            RecordUpdateView, DiagnosticListView, mission)

app_name = ServicesConfig.name

urlpatterns = [
    path('create/', ServiceCreateView.as_view(), name='create'),
    path('', ServiceListView.as_view(), name='home'),
    path('edit/<int:pk>/', ServiceUpdateView.as_view(), name='edit'),
    path('contact/', cache_page(60)(contacts), name='contact'),
    path('company/', cache_page(60)(company), name='company'),
    path('mission/', cache_page(60)(mission), name='mission'),
    path('delete/<int:pk>/', ServiceDeleteView.as_view(), name='delete'),
    path('detail/<int:pk>/', ServiceDetailView.as_view(), name='service_detail'),
    path('record/', RecordCreateView.as_view(), name='record'),
    path('record/list/', RecordListView.as_view(), name='record_list'),
    path('record/delete/<int:pk>/', RecordDeleteView.as_view(), name='record_delete'),
    path('record/edit/<int:pk>/', RecordUpdateView.as_view(), name='record_edit'),
    path('diagnostic/', DiagnosticListView.as_view(), name='diagnostic_list'),]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import UserCreateView, email_confirm, GeneratePasswordView, UsersDetail

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email_confirm/<str:token>/', email_confirm, name='email_confirm'),
    path('reset_password/', GeneratePasswordView.as_view(template_name='reset_password.html'),
         name='reset_password'),
    path('detail/<int:pk>', UsersDetail.as_view(), name='detail'),
]

doctors/models.py
from django.db import models


class Doctor(models.Model):
    name = models.CharField(max_length=250, verbose_name='Имя')
    surname = models.CharField(max_length=250, verbose_name='Фамилия')
    patronymic = models.CharField(max_length=250, verbose_name='Отчество')
    work_experience = models.IntegerField(default=0, verbose_name='Стаж работы')
    specialization = models.CharField(max_length=250, verbose_name='Специализация')
    science = models.TextField(verbose_name='Ученая степень / Категория / Ученое звание')
    post = models.CharField(max_length=250, verbose_name='Должность')
    picture = models.ImageField(upload_to='doctors/', blank=True, null=True, verbose_name='Картинка')

    def __str__(self):
        return f'{self.surname} {self.name} {self.patronymic}'

    class Meta:
        verbose_name = 'Врач'
        verbose_name_plural = 'Врачи'

services/models.py
from django.db import models

from doctors.models import Doctor
from users.models import User


class Service(models.Model):
    name = models.CharField(max_length=250, verbose_name='Услуга')
    description = models.TextField(verbose_name='Описание')
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Цена')
    picture = models.ImageField(upload_to='doctors/', blank=True, null=True, verbose_name='Картинка')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Услуга'
        verbose_name_plural = 'Услуги'


class Record(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Пользователь")
    service = models.ForeignKey(Service, on_delete=models.CASCADE, related_name="Услуги")
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name="Доктор")
    created_at = models.DateTimeField(auto_now_add=True)
    record_time = models.DateField(verbose_name='Дата записи')
    is_active = models.BooleanField(default=True, verbose_name='Отмена записи')

    def __str__(self):
        return f"{self.user.last_name} {self.user.first_name} записан на {self.service.name} к {self.doctor}."

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'
        permissions = [
            ('can_add_record', 'Может добавлять запись'),
            ('can_change_record', 'Может изменять запись'),
            ('can_view_record', 'Может просматривать запись'),
            ('can_delete_record', 'Может удалять запись'),
        ]


class Diagnostic(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Пользователь")
    record = models.ForeignKey(Record, on_delete=models.CASCADE, verbose_name="Запись")
    result = models.TextField(verbose_name='Результат')
    diagnose = models.CharField(max_length=250, verbose_name='Диагноз')

    def __str__(self):
        return f"{self.user.last_name} {self.user.first_name} результат {self.record.service}."

    class Meta:
        verbose_name = 'Диагностика'
        verbose_name_plural = 'Диагностики'
        permissions = [
            ('can_view_diagnostics', 'Может просматривать диагностики'),
        ]

doctors/forms.py
from django import forms

from doctors.models import Doctor
from users.forms import StyleFormMixin


class DoctorForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Doctor
        fields = '__all__'

services/forms.py
from django import forms

from services.models import Service, Record
from users.forms import StyleFormMixin


class ServiceForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Service
        fields = '__all__'


class RecordForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Record
        exclude = ('user', 'is_active')

doctors/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from doctors.forms import DoctorForm
from doctors.models import Doctor
from users.services import get_qs_from_cache


class DoctorListView(ListView):
    model = Doctor
    template_name = 'doctors/home.html'

    def get_queryset(self):
        return get_qs_from_cache(qs=Doctor.objects.all(), key='doctor_list')


class DoctorCreateView(LoginRequiredMixin, CreateView):
    model = Doctor
    form_class = DoctorForm
    success_url = reverse_lazy('doctors:home')
    login_url = "users:login"
    redirect_field_name = "redirect_to"


class DoctorUpdateView(LoginRequiredMixin, UpdateView):
    model = Doctor
    form_class = DoctorForm
    success_url = reverse_lazy('doctors:home')
    login_url = "users:login"
    redirect_field_name = "redirect_to"


class DoctorDeleteView(LoginRequiredMixin, DeleteView):
    model = Doctor
    success_url = reverse_lazy('doctors:home')
    login_url = "users:login"
    redirect_field_name = "redirect_to"


class DoctorDetailView(LoginRequiredMixin, DetailView):
    model = Doctor
    template_name = 'doctors/doctor_detail.html'
    login_url = "users:login"
    redirect_field_name = "redirect_to"

services/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView


from services.forms import ServiceForm, RecordForm
from services.models import Service, Record, Diagnostic

class ServiceListView(ListView):
    model = Service
    template_name = 'services/home.html'



def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'У вас новое сообщение: {name}({phone}): {message}')
    return render(request, 'services/contacts.html')


def home(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'У вас новое сообщение: {name}({phone}): {message}')
    return render(request, 'services/home_page.html')


def company(request):
    return render(request, 'services/company.html')


def mission(request):
    return render(request, 'services/mission.html')


class ServiceCreateView(LoginRequiredMixin, CreateView):
    model = Service
    form_class = ServiceForm
    success_url = reverse_lazy('services:home')
    login_url = "users:login"
    redirect_field_name = "redirect_to"


class ServiceUpdateView(LoginRequiredMixin, UpdateView):
    model = Service
    form_class = ServiceForm
    success_url = reverse_lazy('services:home')
    login_url = "users:login"
    redirect_field_name = "redirect_to"


class ServiceDeleteView(LoginRequiredMixin, DeleteView):
    model = Service
    success_url = reverse_lazy('services:home')
    login_url = "users:login"
    redirect_field_name = "redirect_to"


class ServiceDetailView(LoginRequiredMixin, DetailView):
    model = Service
    template_name = 'services/service_detail.html'
    login_url = "users:login"
    redirect_field_name = "redirect_to"





class RecordCreateView(LoginRequiredMixin, CreateView):
    """Record create """
    model = Record
    form_class = RecordForm
    success_url = reverse_lazy('services:home')
    login_url = "users:login"
    redirect_field_name = "redirect_to"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class RecordListView(ListView):
    model = Record
    template_name = 'services/record_list.html'


class RecordUpdateView(LoginRequiredMixin, UpdateView):
    model = Record
    form_class = RecordForm
    success_url = reverse_lazy('services:record_list')
    login_url = "users:login"
    redirect_field_name = "redirect_to"

    def get_form_class(self):
        user = self.request.user
        if user == self.object.user:
            return RecordForm


class RecordDeleteView(LoginRequiredMixin, DeleteView):
    model = Record
    success_url = reverse_lazy('services:record_list')
    login_url = "users:login"
    redirect_field_name = "redirect_to"




class DiagnosticListView(LoginRequiredMixin, ListView):
    model = Diagnostic
    template_name = 'services/diagnostic_list.html'
    permission_required = 'services.view_diagnostics'

doctors/templates/doctors/doctor_confirm_delete.html
{% extends 'services/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            <p>Хотите удалить доктора "{{ object }}"?</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a href="{% url 'doctors:home'%}" type="submit" class="btn btn-warning">Отменить</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

doctors/templates/doctors/doctor_detail.html
{% extends 'services/base.html' %}
{% load my_tags %}
{% block content %}

    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 g-2">
                <div class="col">
                    <div class="card shadow-sm">
                        <div class="card-body">
                            <div style="text-align: center;"><img src="{{ object.picture | media_filter }}"
                                                              style="width:200px;"></div>
                            <h2 class="card-text">{{ object }}</h2>
                            <p class="card-text">Стаж работы : {{ object.work_experience }} </p>
                            <p class="card-text">Место работы : {{ object.clinical }}</p>
                            <p class="card-text">Специализация : {{ object.specialization }}</p>
                            <p class="card-text">Ученая степень / Категория / Ученое звание: {{ object.science }}</p>
                            <p class="card-text">Должнность : {{ object.post }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-sm btn-outline-secondary">Оставить отзыв</button>
                                    <button><a class="btn btn-sm btn-outline-secondary" href="{% url 'doctors:home' %}">Назад</a></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

doctors/templates/doctors/doctor_form.html
{% extends 'services/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="POST" enctype="multipart/form-data">

        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                    {{ form.as_p }}
                    <br>
                    {% endfor %}
                </div>
            </div>
        </div>

    </form>
</div>
{% endblock %}

doctors/templates/doctors/home.html
{% extends 'services/base.html' %}
{% load my_tags %}
{% block content %}

    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-4">
                {% for object in object_list %}
                    <div class="col">
                <div class="card shadow-sm">

                    <div class="card-body">
                        <div style="text-align: center;"><img src="{{ object.picture | media_filter }}"
                                                              style="width:200px;"></div>
                        <h3 class="card-text">{{ object }}</h3>
                        <p class="card-text">{{ object.post }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'doctors:doctor_detail' object.pk %}"
                                   role="button">Подробнее</a>
                                {% if user.is_superuser %}
                                <a class="btn btn-warning" href="{% url 'doctors:edit' object.pk %}"
                                   role="button">Редактировать</a>
                                <a class="btn btn-danger" href="{% url 'doctors:delete' object.pk %}"
                                   role="button">Удалить</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
                {% endfor %}
        </div>
    </div>
    </div>
{% endblock %}

doctors/templates/doctors/service_confirm_delete.html
{% extends 'services/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            <p>Хотите удалить "{{ object.name }}"?</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a href="{% url 'services:home'%}" type="submit" class="btn btn-warning">Отменить</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

doctors/templates/doctors/service_form.html
{% extends 'services/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="POST" enctype="multipart/form-data">

        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                    {{ form.as_p }}
                    <br>
                    {% endfor %}
                </div>
            </div>
        </div>

    </form>
</div>
{% endblock %}