config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from config import settings
from services.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home_page'),
    path('services/', include('services.urls', namespace='services')),
    path('doctors/', include('doctors.urls', namespace='doctors')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from services.apps import ServicesConfig
from services.views import (contacts, ServiceDetailView, ServiceListView, ServiceCreateView, ServiceUpdateView,
                            ServiceDeleteView, company, RecordCreateView, RecordListView, RecordDeleteView,
                            RecordUpdateView, DiagnosticListView, mission)

app_name = ServicesConfig.name

urlpatterns = [
    path('create/', ServiceCreateView.as_view(), name='create'),
    path('', ServiceListView.as_view(), name='home'),
    path('edit/<int:pk>/', ServiceUpdateView.as_view(), name='edit'),
    path('contact/', cache_page(60)(contacts), name='contact'),
    path('company/', cache_page(60)(company), name='company'),
    path('mission/', cache_page(60)(mission), name='mission'),
    path('delete/<int:pk>/', ServiceDeleteView.as_view(), name='delete'),
    path('detail/<int:pk>/', ServiceDetailView.as_view(), name='service_detail'),
    path('record/', RecordCreateView.as_view(), name='record'),
    path('record/list/', RecordListView.as_view(), name='record_list'),
    path('record/delete/<int:pk>/', RecordDeleteView.as_view(), name='record_delete'),
    path('record/edit/<int:pk>/', RecordUpdateView.as_view(), name='record_edit'),
    path('diagnostic/', DiagnosticListView.as_view(), name='diagnostic_list'),]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import UserCreateView, email_confirm, GeneratePasswordView, UsersDetail

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email_confirm/<str:token>/', email_confirm, name='email_confirm'),
    path('reset_password/', GeneratePasswordView.as_view(template_name='reset_password.html'),
         name='reset_password'),
    path('detail/<int:pk>', UsersDetail.as_view(), name='detail'),
]

services/models.py
from django.db import models

from doctors.models import Doctor
from users.models import User


class Service(models.Model):
    name = models.CharField(max_length=250, verbose_name='Услуга')
    description = models.TextField(verbose_name='Описание')
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Цена')
    picture = models.ImageField(upload_to='doctors/', blank=True, null=True, verbose_name='Картинка')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Услуга'
        verbose_name_plural = 'Услуги'


class Record(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Пользователь")
    service = models.ForeignKey(Service, on_delete=models.CASCADE, related_name="Услуги")
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name="Доктор")
    created_at = models.DateTimeField(auto_now_add=True)
    record_time = models.DateField(verbose_name='Дата записи')
    is_active = models.BooleanField(default=True, verbose_name='Отмена записи')

    def __str__(self):
        return f"{self.user.last_name} {self.user.first_name} записан на {self.service.name} к {self.doctor}."

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'
        permissions = [
            ('can_add_record', 'Может добавлять запись'),
            ('can_change_record', 'Может изменять запись'),
            ('can_view_record', 'Может просматривать запись'),
            ('can_delete_record', 'Может удалять запись'),
        ]


class Diagnostic(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Пользователь")
    record = models.ForeignKey(Record, on_delete=models.CASCADE, verbose_name="Запись")
    result = models.TextField(verbose_name='Результат')
    diagnose = models.CharField(max_length=250, verbose_name='Диагноз')

    def __str__(self):
        return f"{self.user.last_name} {self.user.first_name} результат {self.record.service}."

    class Meta:
        verbose_name = 'Диагностика'
        verbose_name_plural = 'Диагностики'
        permissions = [
            ('can_view_diagnostics', 'Может просматривать диагностики'),
        ]

services/forms.py
from django import forms

from services.models import Service, Record
from users.forms import StyleFormMixin


class ServiceForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Service
        fields = '__all__'


class RecordForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Record
        exclude = ('user', 'is_active')

services/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView


from services.forms import ServiceForm, RecordForm
from services.models import Service, Record, Diagnostic

class ServiceListView(ListView):
    model = Service
    template_name = 'services/home.html'



def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'У вас новое сообщение: {name}({phone}): {message}')
    return render(request, 'services/contacts.html')


def home(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'У вас новое сообщение: {name}({phone}): {message}')
    return render(request, 'services/home_page.html')


def company(request):
    return render(request, 'services/company.html')


def mission(request):
    return render(request, 'services/mission.html')


class ServiceCreateView(LoginRequiredMixin, CreateView):
    model = Service
    form_class = ServiceForm
    success_url = reverse_lazy('services:home')
    login_url = "users:login"
    redirect_field_name = "redirect_to"


class ServiceUpdateView(LoginRequiredMixin, UpdateView):
    model = Service
    form_class = ServiceForm
    success_url = reverse_lazy('services:home')
    login_url = "users:login"
    redirect_field_name = "redirect_to"


class ServiceDeleteView(LoginRequiredMixin, DeleteView):
    model = Service
    success_url = reverse_lazy('services:home')
    login_url = "users:login"
    redirect_field_name = "redirect_to"


class ServiceDetailView(LoginRequiredMixin, DetailView):
    model = Service
    template_name = 'services/service_detail.html'
    login_url = "users:login"
    redirect_field_name = "redirect_to"





class RecordCreateView(LoginRequiredMixin, CreateView):
    """Record create """
    model = Record
    form_class = RecordForm
    success_url = reverse_lazy('services:home')
    login_url = "users:login"
    redirect_field_name = "redirect_to"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class RecordListView(ListView):
    model = Record
    template_name = 'services/record_list.html'


class RecordUpdateView(LoginRequiredMixin, UpdateView):
    model = Record
    form_class = RecordForm
    success_url = reverse_lazy('services:record_list')
    login_url = "users:login"
    redirect_field_name = "redirect_to"

    def get_form_class(self):
        user = self.request.user
        if user == self.object.user:
            return RecordForm


class RecordDeleteView(LoginRequiredMixin, DeleteView):
    model = Record
    success_url = reverse_lazy('services:record_list')
    login_url = "users:login"
    redirect_field_name = "redirect_to"




class DiagnosticListView(LoginRequiredMixin, ListView):
    model = Diagnostic
    template_name = 'services/diagnostic_list.html'
    permission_required = 'services.view_diagnostics'

services/templates/services/includes/inc_menu.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">

    <h5 class="my-0 mr-md-auto font-weight-normal">МЕДСити</h5>

    <ul class="nav nav-tabs">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button"
               aria-expanded="false">Навигация</a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'home_page' %}">Главная</a></li>
                <li><a class="dropdown-item" href="{% url 'services:home' %}">Услуги</a></li>
                <li><a class="dropdown-item" href="{% url 'doctors:home' %}">Врачи</a></li>
                <li><a class="dropdown-item" href="{% url 'services:contact' %}">Контакты</a></li>

            </ul>
        </li>
        {% if user.is_superuser %}
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button"
               aria-expanded="false">Админ</a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'services:create' %}">Создать Услугу</a></li>
                <li><a class="dropdown-item" href="{% url 'doctors:create' %}">Добавить доктора</a></li>
                <li><a class="dropdown-item" href="{% url 'services:record_list' %}">Просмотр записей</a></li>
            </ul>
        </li>
        {% endif %}
        {% if user.is_authenticated %}
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button"
               aria-expanded="false">Пользователь</a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'services:record' %}">Записаться на прием</a></li>
                <li><a class="dropdown-item" href="{% url 'services:record_list' %}">Мои записи</a></li>
                <li><a class="dropdown-item" href="{% url 'services:diagnostic_list' %}">Результаты</a></li>
                <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a></li>
            </ul>
        </li>

        {% else %}
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button"
               aria-expanded="false">Пользователь</a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'users:login' %}">Вход</a></li>
                <li><a class="dropdown-item" href="{% url 'users:register' %}">Зарегестрироваться</a></li>
            </ul>
        </li>
        {% endif %}

    </ul>
</div>