config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from config import settings
from services.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home_page'),
    path('services/', include('services.urls', namespace='services')),
    path('doctors/', include('doctors.urls', namespace='doctors')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from services.apps import ServicesConfig
from services.views import (contacts, ServiceDetailView, ServiceListView, ServiceCreateView, ServiceUpdateView,
                            ServiceDeleteView, company, RecordCreateView, RecordListView, RecordDeleteView,
                            RecordUpdateView, DiagnosticListView, mission)

app_name = ServicesConfig.name

urlpatterns = [
    path('create/', ServiceCreateView.as_view(), name='create'),
    path('', ServiceListView.as_view(), name='home'),
    path('edit/<int:pk>/', ServiceUpdateView.as_view(), name='edit'),
    path('contact/', cache_page(60)(contacts), name='contact'),
    path('company/', cache_page(60)(company), name='company'),
    path('mission/', cache_page(60)(mission), name='mission'),
    path('delete/<int:pk>/', ServiceDeleteView.as_view(), name='delete'),
    path('detail/<int:pk>/', ServiceDetailView.as_view(), name='service_detail'),
    path('record/', RecordCreateView.as_view(), name='record'),
    path('record/list/', RecordListView.as_view(), name='record_list'),
    path('record/delete/<int:pk>/', RecordDeleteView.as_view(), name='record_delete'),
    path('record/edit/<int:pk>/', RecordUpdateView.as_view(), name='record_edit'),
    path('diagnostic/', DiagnosticListView.as_view(), name='diagnostic_list'),]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import UserCreateView, email_confirm, GeneratePasswordView, UsersDetail

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email_confirm/<str:token>/', email_confirm, name='email_confirm'),
    path('reset_password/', GeneratePasswordView.as_view(template_name='reset_password.html'),
         name='reset_password'),
    path('detail/<int:pk>', UsersDetail.as_view(), name='detail'),
]

services/models.py
from django.db import models

from doctors.models import Doctor
from users.models import User


class Service(models.Model):
    name = models.CharField(max_length=250, verbose_name='Услуга')
    description = models.TextField(verbose_name='Описание')
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Цена')
    picture = models.ImageField(upload_to='doctors/', blank=True, null=True, verbose_name='Картинка')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Услуга'
        verbose_name_plural = 'Услуги'


class Record(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Пользователь")
    service = models.ForeignKey(Service, on_delete=models.CASCADE, related_name="Услуги")
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name="Доктор")
    created_at = models.DateTimeField(auto_now_add=True)
    record_time = models.DateField(verbose_name='Дата записи')
    is_active = models.BooleanField(default=True, verbose_name='Отмена записи')

    def __str__(self):
        return f"{self.user.last_name} {self.user.first_name} записан на {self.service.name} к {self.doctor}."

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'
        permissions = [
            ('can_add_record', 'Может добавлять запись'),
            ('can_change_record', 'Может изменять запись'),
            ('can_view_record', 'Может просматривать запись'),
            ('can_delete_record', 'Может удалять запись'),
        ]


class Diagnostic(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Пользователь")
    record = models.ForeignKey(Record, on_delete=models.CASCADE, verbose_name="Запись")
    result = models.TextField(verbose_name='Результат')
    diagnose = models.CharField(max_length=250, verbose_name='Диагноз')

    def __str__(self):
        return f"{self.user.last_name} {self.user.first_name} результат {self.record.service}."

    class Meta:
        verbose_name = 'Диагностика'
        verbose_name_plural = 'Диагностики'
        permissions = [
            ('can_view_diagnostics', 'Может просматривать диагностики'),
        ]

services/forms.py
from django import forms

from services.models import Service, Record
from users.forms import StyleFormMixin


class ServiceForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Service
        fields = '__all__'


class RecordForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Record
        exclude = ('user', 'is_active')

services/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView


from services.forms import ServiceForm, RecordForm
from services.models import Service, Record, Diagnostic

class ServiceListView(ListView):
    model = Service
    template_name = 'services/home.html'



def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'У вас новое сообщение: {name}({phone}): {message}')
    return render(request, 'services/contacts.html')


def home(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'У вас новое сообщение: {name}({phone}): {message}')
    return render(request, 'services/home_page.html')


def company(request):
    return render(request, 'services/company.html')


def mission(request):
    return render(request, 'services/mission.html')


class ServiceCreateView(LoginRequiredMixin, CreateView):
    model = Service
    form_class = ServiceForm
    success_url = reverse_lazy('services:home')
    login_url = "users:login"
    redirect_field_name = "redirect_to"


class ServiceUpdateView(LoginRequiredMixin, UpdateView):
    model = Service
    form_class = ServiceForm
    success_url = reverse_lazy('services:home')
    login_url = "users:login"
    redirect_field_name = "redirect_to"


class ServiceDeleteView(LoginRequiredMixin, DeleteView):
    model = Service
    success_url = reverse_lazy('services:home')
    login_url = "users:login"
    redirect_field_name = "redirect_to"


class ServiceDetailView(LoginRequiredMixin, DetailView):
    model = Service
    template_name = 'services/service_detail.html'
    login_url = "users:login"
    redirect_field_name = "redirect_to"





class RecordCreateView(LoginRequiredMixin, CreateView):
    """Record create """
    model = Record
    form_class = RecordForm
    success_url = reverse_lazy('services:home')
    login_url = "users:login"
    redirect_field_name = "redirect_to"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class RecordListView(ListView):
    model = Record
    template_name = 'services/record_list.html'


class RecordUpdateView(LoginRequiredMixin, UpdateView):
    model = Record
    form_class = RecordForm
    success_url = reverse_lazy('services:record_list')
    login_url = "users:login"
    redirect_field_name = "redirect_to"

    def get_form_class(self):
        user = self.request.user
        if user == self.object.user:
            return RecordForm


class RecordDeleteView(LoginRequiredMixin, DeleteView):
    model = Record
    success_url = reverse_lazy('services:record_list')
    login_url = "users:login"
    redirect_field_name = "redirect_to"




class DiagnosticListView(LoginRequiredMixin, ListView):
    model = Diagnostic
    template_name = 'services/diagnostic_list.html'
    permission_required = 'services.view_diagnostics'

services/templates/services/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">


    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
    <title>МЕДСити</title>

</head>
<body>
<header data-bs-theme='blue'>
    {% include 'services/includes/inc_menu.html' %}
</header>


{% block content %}
{% endblock %}

<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            МЕДСити
            <small class="d-block mb-3 text-muted">&copy; 2023</small>
        </div>
        <div class="col-6 col-md">
            <h5>Карта сайта</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="{% url 'services:home' %}">Услуги</a></li>
                <li><a class="text-muted" href="#">Клиники</a></li>
                <li><a class="text-muted" href="#">Пациентам</a></li>
                <li><a class="text-muted" href="{% url 'doctors:home' %}">Врачи</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Статьи</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="{% url 'services:company' %}">О компании</a></li>
                <li><a class="text-muted" href="{% url 'services:contact' %}">Контакты</a></li>
                <li><a class="text-muted" href="{% url 'services:mission' %}">Миссия</a></li>
            </ul>
        </div>
    </div>
</footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

services/templates/services/company.html
{% extends 'services/base.html' %}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">О холдинге «МЕДСити»</h1>
    </div>
    <div class="b-about-director">
        <div class="container">
            <div class="b-about-director__box">
                <div class="b-about-director__image">
                    <picture>
                        <source srcset="https://www.smclinic.ru/upload/iblock/528/bvc0r7ic474vux3pzy1jg5ilz0cp06bc.jpg.webp"
                                type="image/webp">
                        <img loading="lazy"
                             src="https://www.smclinic.ru/upload/iblock/528/bvc0r7ic474vux3pzy1jg5ilz0cp06bc.jpg.webp">
                    </picture>
                </div>
                <div class="b-about-director__text">
                    <div class="text">
                        <p>
                            <b>От первого лица</b>
                        </p>
                        <p>
                            Холдинг «МЕДСити» - одна из крупнейших сетей многопрофильных медицинских
                            центров для взрослых и детей. Холдинг входит в топ-150 частных клиник по оценкам
                            РБК.
                        </p>
                        <p>
                            Мы ведём свою историю с 2002 года. Сейчас у нас работают 3 многопрофильных
                            клиник в Москве,которые открыты для вас ежедневно, включая выходные и праздничные дни.
                        </p></div>
                    <div class="b-about-director__sign">
                        <div><b>Сергей Венцеславович Сырский</b><br>генеральный директор группы компаний
                            «МЕДСити»
                        </div>

                        <picture>
                            <source srcset="https://www.smclinic.ru/upload/iblock/37c/8kknhc7qo7zxpebzf1oir6o5p3fgspb
                            i.png.webp"
                                    type="image/webp">
                            <img loading="lazy"
                                 src="https://www.smclinic.ru/upload/iblock/37c/8kknhc7qo7zxpebzf1oir6o5p3fgspbi.png.webp">
                        </picture>
                    </div>
                </div>
            </div>

            <div class="b-about-team">
                <div class="container">
                    <div class="b-about-team__box">
                        <div class="b-about-team__left">
                            <div class="text">
                                <div style="text-align: center;"><h2>Команда «МЕДСити»</h2>
                                    <picture>
                                        <source srcset="https://avatars.mds.yandex.net/i?id=9539f5aba58beebb4bb4bf9bf63ec8b7_l-5904837-images-thumbs&n=13"
                                                type="image/webp" style="width:800px;">
                                        <img loading="lazy"
                                             src="https://avatars.mds.yandex.net/i?id=9539f5aba58beebb4bb4bf9bf63ec8b7_l-5904837-images-thumbs&n=13"
                                             style="width:800px;">
                                    </picture>
                                </div>
                                <p>
                                    В наших центрах работают опытные специалисты, которые с вниманием относятся к
                                    каждому пациенту. Это профессионалы, которые станут вашими партнёрами в сохранении
                                    здоровья.
                                </p>
                                <p>
                                    В медицинских центрах «СМ-Клиника» работает более 90 квалифицированных врачей
                                    различных специальностей, среди которых более 3 кандидатов медицинских наук, более
                                    2 докторов медицинских наук, 6 профессоров, 1 академика РАМН, 6 доцентов и
                                    старших научных сотрудников.
                                </p>
                                <p>
                                    В наших медицинских центрах работают врачи как самых востребованных медицинских
                                    специальностей: терапевты, кардиологи, урологи, гинекологи, офтальмологи,
                                    оториноларингологи, хирурги и другие, так и редких: генетики, репродуктологи,
                                    эмбриологи, гепатологи и другие.
                                </p>
                                <p>
                                    В детских отделениях ведут приём доктора, специализирующиеся на лечении детей с
                                    первых дней жизни до совершеннолетия.
                                </p></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

services/templates/services/contacts.html
{% extends 'services/base.html' %}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Контакты</h1>
    </div>

    <div class="container">
        <div class="row text-start">
            <div class="col-lg-9 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <table class="table table-striped">
                            <tr>
                                <td class="w-25">Страна</td>
                                <td>Россия</td>
                            </tr>
                            <tr>
                                <td class="w-25">ИНН</td>
                                <td>91-1144442</td>
                            </tr>
                            <tr>
                                <td class="w-25">Адрес</td>
                                <td>Москва,Патриотическая,9А</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" action="" class="form-floating">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="name">Имя</label>
                                <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                       required>
                            </div>
                            <div class="mb-3">
                                <label for="phone">Телефон</label>
                                <input type="text" name="phone" class="form-control" id="phone"
                                       placeholder="Контактный телефон" required>
                            </div>
                            <div class="mb-3">
                                <label for="message">Сообщение</label>
                                <textarea type="text" name="message" class="form-control" id="message"
                                          placeholder="Напишите нам"
                                          required></textarea>
                            </div>
                            <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    <img src="https://avatars.dzeninfra.ru/get-zen_doc/1686199/pub_640b0f90c54e2840dc1f27a3_640b17172641cf5c1735047d/scale_1200" class="img-fluid" alt="...">
    </div>
{% endblock %}

services/templates/services/diagnostic_list.html
{% extends 'services/base.html' %}
{% block content %}
    <body>
    {% for object in object_list %}
        {% if user == object.user or user.is_superuser and object %}
            <div class="album py-5 bg-body-tertiary">
                <div class="row row-cols-2 row-cols-sm-4 row-cols-md-3 g-4">

                    <div class="card" style="width: 18rem;">
                        <div class="card-header text-center">
                            Результат Диагностики
                        </div>
                        <ul class="list-group list-group-flush text-center">
                            <li class="list-group-item text-success">Номер записи: {{ object.record.pk }}</li>
                            <li class="list-group-item text-success">Пациент: {{ object.user }}</li>
                            <li class="list-group-item text-secondary">Результат: {{ object.result }}</li>
                            <li class="list-group-item text-warning">Диагноз: {{ object.diagnose }}</li>
                            <li class="list-group-item text">Врач: {{ object.record.doctor.name }}
                                {{ object.record.doctor.surname }}</li>
                        </ul>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="card-header text-center">
            <div style="text-align: center;"><h1 class="display-2">Результата диагностики пока нет</h1></div>
            </div>
        {% endif %}
    {% endfor %}
    </body>
{% endblock %}

services/templates/services/home.html
{% extends 'services/base.html' %}
{% load my_tags %}
{% block content %}

    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-4">
                {% for object in object_list %}
                    <div class="col">
                        <div class="card shadow-sm">
                            <div style="text-align: center;"><img src="{{ object.picture | media_filter }}"
                                                                  style="width:200px;"></div>
                            <div class="card-body">
                                <h3 class="card-text">{{ object }}</h3>
                                <p class="card-text">{{ object.description | slice:100 }}</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a class="btn btn-primary" href="{% url 'services:service_detail' object.pk %}"
                                           role="button">Подробнее</a>
                                        {% if user.is_superuser %}
                                            <a class="btn btn-warning" href="{% url 'services:edit' object.pk %}"
                                               role="button">Редактировать</a>
                                        {% endif %}
                                        {% if user.is_superuser %}
                                            <a class="btn btn-danger" href="{% url 'services:delete' object.pk %}"
                                               role="button">Удалить</a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

services/templates/services/home_page.html
{% extends 'services/base.html' %}
{% load my_tags %}
{% block content %}



    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">О нашей компании</h1>
            <p class="lead">МЕДСити - Мы внедряем в реальную клиническую практику инновационные технологии,
                    повышающие эффективность и безопасность медицинской помощи.</p>
            <p class="lead">Предоставляем услуги в области: диагностики <a href={% url 'services:home'%}>подробнее</a></p>
            <p class="lead"> <a href={% url 'services:contact'%}>Контактная информация</a></p>
            <p class="lead"> <a href={% url 'services:company'%}>Подробнее о нас</a></p>
    </div>

    <div style="text-align: center;"><h2>Акции и предложения месяца</h2></div>
    <div class="col-12 text-center">
        <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active" data-bs-interval="10000">
                    <img src="https://partner.napopravku.ru/blog2/wp-content/uploads/2020/02/TV-1024x576.jpg"
                          alt="...">
                </div>
                <div class="carousel-item">
                    <img src="https://www.tonus.nnov.ru/wp-content/uploads/2024/01/kompleks-muzhskoe-zdorove-so-skidkoj-768x350.jpg"
                          alt="...">
                </div>
                <div class="carousel-item">
                    <img src="https://medlineservice.ru/upload/iblock/3d7/np8jfw9knnf9z57r5ucve4hmwq5oaso6.png"  alt="...">
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="container">
    <form class="row g-3 needs-validation" style="width: 420%;" >
    <div class="col-lg-3 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <div style="text-align: center;"><h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4></div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="" class="form-floating">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="name">Имя</label>
                                <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                       required>
                            </div>
                            <div class="mb-3">
                                <label for="phone">Телефон</label>
                                <input type="text" name="phone" class="form-control" id="phone"
                                       placeholder="Контактный телефон" required>
                            </div>
                            <div class="mb-3">
                                <label for="message">Сообщение</label>
                                <textarea type="text" name="message" class="form-control" id="message"
                                          placeholder="Напишите нам"
                                          required></textarea>
                            </div>
                            <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                        </form>
                    </div>
                </div>
            </div>
    </form>
    </div>

{% endblock %}

services/templates/services/product_confirm_delete.html
{% extends 'services/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            <p>Хотите удалить "{{ object.name }}"?</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a href="{% url 'catalog:home'%}" type="submit" class="btn btn-warning">Отменить</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

services/templates/services/product_form.html
{% extends 'services/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="POST" enctype="multipart/form-data">

        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                    {{ form.as_p }}
                    <br>
                    {% endfor %}
                </div>
            </div>
        </div>

    </form>
</div>
{% endblock %}

services/templates/services/record_confirm_delete.html
{% extends 'services/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            <p>Хотите отменить "{{ object.service }}"?</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a href="{% url 'services:record_list'%}" type="submit" class="btn btn-warning">Отменить</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

services/templates/services/record_form.html
{% extends 'services/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="POST" enctype="multipart/form-data">

        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        Записаться
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

services/templates/services/record_list.html
{% extends 'services/base.html' %}
{% load my_tags %}
{% block content %}

    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-4">
                {% for record in object_list %}
                    {% if user == record.user or user.is_superuser %}
                        <div class="col">
                            <div class="card shadow-sm">
                                <div class="card-body">
                                    <h5 class="card-text">Запись {{ record.id }} </h5>
                                    <p class="card-text">{{ record }} </p>
                                    <p class="card-text">Запись создана: {{ record.created_at }}</p>
                                    <p class="card-text">Ожидаем вас: {{ record.record_time }}</p>
                                    {% if record.is_active %}
                                        <p class="card-text">Ожидайте результата</p>
                                    {% else %}
                                        <p class="card-text">Результат готов</p>
                                    {% endif %}
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">
                                            {% if user == record.user or user.is_superuser %}
                                                <a class="btn btn-warning"
                                                   href="{% url 'services:record_edit' record.pk %}"
                                                   role="button">Изменить</a>
                                                <a class="btn btn-danger"
                                                   href="{% url 'services:record_delete' record.pk %}"
                                                   role="button">Отменить</a>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}